name: Deploy To EC2

on:
    push:
        branches:
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Github Repository 파일 불러오기
              uses: actions/checkout@v4

            - name: NODE 설치
              uses: actions/setup-node@v4
              with:
                node-version: "20"

            - name: 의존성(라이브러리) 설치
              run: npm ci
                
            - name: .env 파일 만들기
              run: |
                echo '${{ secrets.ENV }}' > .env

            - name: 빌드
              run: npm run build

            - name: 압축하기
              run: tar -czvf project.tar.gz dist .env package.json package-lock.json

            - name: SCP로 EC2에 빌드된 파일 전송하기
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                source: project.tar.gz
                target: /home/ubuntu/BE-mini-game-world/tobe

            - name: SSH로 EC2에 접속하기
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                script_stop: true
                script: |
                  rm -rf /home/ubuntu/BE-mini-game-world/current
                  mkdir /home/ubuntu/BE-mini-game-world/current
                  mv /home/ubuntu/BE-mini-game-world/tobe/project.tar.gz /home/ubuntu/BE-mini-game-world/current/project.tar.gz
                  cd /home/ubuntu/BE-mini-game-world/current
                  tar -xvf project.tar.gz
                  npm ci
                  pm2 kill
                  pm2 start dist/main.js --name "mini-game-world"
